config/routes.rb
Tagcoin::Application.routes.draw do
  get "/" => "site#index"
  get "techspecs/" => "site#techspecs"
  get "sourcecode" => "site#sourcecode"
  get "uses/" => "site#uses"
  get "apps/" => "site#apps"
  get "merchants/" => "site#merchants"
  get "tagverts/" => "site#tagverts"

  root 'site#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def app_title(page_title)
        base_title = "Tagcoin"
        if page_title.empty?
            base_title
        else
            "#{base_title} | #{page_title}"
        end
    end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/_header.html.haml
.navbar.bs-docs-nav{:role => "banner"}
  .container
    /
      <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
      <span class="sr-only">Toggle Navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      </div>
      <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      <ul class="nav navbar-nav">
      <li><haml:loud> link_to(&amp;#39;Technical&amp;#39;, techspecs_path) </haml:loud></li>
      <li><haml:loud> link_to(&amp;#39;Uses&amp;#39;, &amp;#39;#&amp;#39;) </haml:loud></li>
      <li><haml:loud> link_to(&amp;#39;Apps&amp;#39;, &amp;#39;#&amp;#39;) </haml:loud></li>
      <li><haml:loud> link_to(&amp;#39;Merchants&amp;#39;, &amp;#39;#&amp;#39;) </haml:loud></li>
      <li><haml:loud> link_to(&amp;#39;Tagverts&amp;#39;, &amp;#39;#&amp;#39;) </haml:loud></li>
      </ul>
      </nav>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= app_title(yield(:page_title))
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = stylesheet_link_tag    "icomoon"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    %link{:href => "http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "http://fonts.googleapis.com/css?family=Oswald:400,700", :rel => "stylesheet", :type => "text/css"}/
  %body
    = render 'layouts/header'
    .content
      .container
        = yield
        %br/
        %br/
        %br/
    %footer

app/views/site/index.html.haml
- provide(:page_title, "Home")
.row
  .col-md-12
    #da-slider.da-slider
      .da-slide
        %h2 TAGcoin
        %p A cryptographic coin specifically created with the rewards market in mind. A coin that in itself will earn rewards.
        .da-img= image_tag("parallax/1.png", :alt => "image01")
      .da-slide
        %h2 Created by Tagbond
        %p Created by Tagbond, the rewards site where you can search for great deals and earn rewards, including Tagcoin
        .da-img= image_tag("parallax/2.png", :alt => "image02")
      .da-slide
        %h2 Flexible
        %p Earn it, spend it, save it, trade it.
        .da-img= image_tag("parallax/3.png", :alt => "image03")
      .da-slide
        %h2 Earn TAG today
        %p Look for websites and merchants offering TAG.
        .da-img= image_tag("parallax/4.png", :alt => "image04")
      %nav.da-arrows
        %span.da-arrows-prev
        %span.da-arrows-next
    .bor
    .main-content
      .row
        .col-md-7
          %h2 The World's First Rewards Coin
          %p.main-meta with a market ready to accept it
          %p TagCoin is the world's first universal rewards coin. It is a cryptocurrency that merges the best out of rewards and real cash programs. It is two sides of one coin: a loyalty program used to generate engagement, and a medium of exchange for products/services. With an ecosystem ready to make use of the coin, it offers both users and merchants a more flexible, effective and easier way to engage with each other.
        .col-md-5
          .main-box
            %h4 Features
            %p TagCoin will be the primary currency used within Tagbond and TagCash. It is designed with the following objectives in mind:
            %ul
              %li Fairness - Difficulty will start out at a reasonable value so no one can get an unfair advantage
              %li Sustainability - Parameters have been chosen such that TagCoin can survive well into the future
              %li Services - Tagbond and TagCash are just the start of the ecosystem that will we be building around TagCoin
              %li Transparency - Open Conversation and discussion with the founders and staff within Tagbond
%br/
%br/
%br/
.row
  = link_to("/downloads/tagcoin-qt.zip") do
    .col-md-3.col-sm-6
      .afeature
        .afmatter
          %i.icon-windows8
          %h4 Windows Client
  = link_to("/downloads/TagCoin-Mac.zip") do
    .col-md-3.col-sm-6
      .afeature
        .afmatter
          %i.icon-apple
          %br/
          %br/
          %h4 Mac OSX Client
  = link_to("/downloads/tagcoin-qt-ubuntu.zip") do
    .col-md-3.col-sm-6
      .afeature
        .afmatter
          %i.icon-tux
          %br/
          %br/
          %h4 Ubuntu Client
  = link_to(sourcecode_path) do
    .col-md-3.col-sm-6
      .afeature
        .afmatter
          %i.icon-github
          %br/
          %br/
          %h4 Source Code
:javascript
  $(function(){
      $('#da-slider').cslider({
          autoplay : true,
          interval : 6000
      });
  });

app/views/site/sourcecode.html.haml
/ Title
%title Service Page - TagCash
<?php include 'header.php'; ?>
/ Content strats
.content
  .container
    .row
      .col-md-12
        / Service starts
        .servic
          .row
            .col-md-12
              / Service hero
              .hero
                / Title. Don't forget the <span> tag
                %h3
                  %span Service
                / para
                %p Praesent at tellus porttitor nisl porttitor sagittis. Mauris in massa ligula, a tempor nulla. Ut tempus interdum mauris vel vehicula. Nulla ullamcorper tortor commodo in sagittis est accumsan.
              / Service
              / Service list. Note down the class name before editing.
              .row
                .col-md-6
                  / Service 1. Class name - "serv-a"
                  .serv-a
                    .serv
                      .simg
                        / Font awesome icon.
                        %i.icon-gift
                      / Service title
                      %h4 Source Code (zip)
                      / Service para
                      %p Fusce imperdiet, risus eget viverra faucibus, diam mi vestibulum libero, tellus magna nec enim. Nunc dapibus varius interdum.
                      %button.btn.btn-danger Download
                      %br/
                  / Service 2. Class name - "serv-b"
                  .serv-b
                    .serv
                      .simg
                        %i.icon-home
                      %h4 Source Code
                      %p Fusce imperdiet, risus eget viverra faucibus, diam mi vestibulum libero, tellus magna nec enim. Nunc dapibus varius interdum.
                      %button.btn.btn-danger GitHub
                  .clearfix
                .col-md-6
                  / Service 3. Class name - "serv-a"
                  .serv-a
                    .serv
                      .simg
                        %i.icon-bullhorn
                      %h4 QT Format
                      %p Fusce imperdiet, risus eget viverra faucibus, diam mi vestibulum libero, tellus magna nec enim. Nunc dapibus varius interdum.
                      %button.btn.btn-danger GitHub
                  / Service 4. Class name - "serv-b"
                  .serv-b
                    .serv
                      .simg
                        %i.icon-cloud
                      %h4 TagCoin Wallet (Beta)
                      %p Fusce imperdiet, risus eget viverra faucibus, diam mi vestibulum libero, tellus magna nec enim. Nunc dapibus varius interdum.
                      %button.btn.btn-danger Download
                  .clearfix

app/views/site/techspecs.html.haml
- provide(:page_title, "Technical Specifications")